### ISSUE TITLE
Releases visible on repo's main page?

### ISSUE THREAD

**Issue by Theodlz** [nabeelre/BTSbot#1]
Super cool logo btw! Love it.

My GitHub's main page showed me the new release, but clicking on that notification I got confused because it does not show up on the repo's page. 

Unless there is a reason to do otherwise, I would suggest adding the latest release's widget thingy on the right side of the screen under the repo's information/description.

**Comment by nabeelre** [comment]
Compliments to DALLE for the logo! Took a while to get what I wanted but it was certainly quicker than making it myself.

Just made the releases visible. I had it hidden previously because there were none. 

Thanks
